### ISSUE TITLE
Support multi repo workspace

### ISSUE THREAD

**Issue by nampas** [reduckted/GitWebLinks#10]
Unless I'm missing something, this plugin doesn't work when the VSCode workspace encompasses multiple repositories. In my case, I have one workspace (~/code), that has many subdirectories each of which contains their own git repository.
```
[11:52:38.032] Could not find the root directory of the Git repository.
[11:52:38.032] Could not find Git info for path '/Users/npastor/code'.
```
I assume the extension is just looking in that workspace root for a git repo. Would it be hard to traverse up (or down) the the directory tree to find a git repo?

**Comment by reduckted** [comment]
Hi @nampas. Sorry for not responding sooner.

This is supported from v2.1 which was published earlier this week.
