### ISSUE TITLE
Feature request: inverse operation, start with a GitHub URL which contains hash line number(s), and open the file in VSCode at the designated line / code selection

### ISSUE THREAD

**Issue by danielweck** [reduckted/GitWebLinks#11]
Hello, great extension, thank you!
Very useful for code peer reviews over Slack / instant messaging, to exchange URLs whilst working locally from VSCode.
However the inverse functionality would be very useful too.

For example I would like to be able to copy such URL: `https://github.com/reduckted/vscode-gitweblinks/blob/1244479c00a2192e6100f49296fd97f92bb8e4e5/src/utilities/ServerUrl.ts#L2-L4`

https://github.com/reduckted/vscode-gitweblinks/blob/1244479c00a2192e6100f49296fd97f92bb8e4e5/src/utilities/ServerUrl.ts#L2-L4

...and to show `src/utilities/ServerUrl.ts` in VSCode with the code selection line 2-4 (extracted from the URL `#L2-L4`).

Any thoughts?

**Comment by reduckted** [comment]
Great idea! I have a few thoughts on how this could be done, so I'll have a shot at it this weekend.

**Comment by reduckted** [comment]
This is now available in v2.3.0 🚀 

Details are in the readme: https://github.com/reduckted/vscode-gitweblinks#open-the-file-from-a-link

**Comment by danielweck** [comment]
Very nice, thank you :)

Until now I was using the CMD+OPTION+O+U command implemented by this VSCode extension:
https://github.com/alexander-yu/vscode-open

I like your UX integration better :)

My favourite integration for the inverse operation is:
https://github.com/d4rkr00t/vscode-open-in-github

Cheers, Daniel
