### ISSUE TITLE
Azure DevOps Server

### ISSUE THREAD

**Issue by kvart714** [reduckted/GitWebLinks#13]
Please, add support of custom url for Azure DevOps|

Url examples:
**file:** 
https://{custom.site.net}/tfs/DefaultCollection/{project}/_git/{repository}?path=%2FConfig%2FWebApplications&version=GBdevelop

**selection:** 
https://{custom.site.net}/tfs/DefaultCollection/{project}/_git/{repository}?path=%2FConfig%2FWebApplications%2Freadme.txt&version=GBdevelop&line=1&lineEnd=1&lineStartColumn=14&lineEndColumn=23&lineStyle=plain

**Comment by kvart714** [comment]
It works for me
https://github.com/reduckted/vscode-gitweblinks/pull/14

**Comment by reduckted** [comment]
Available in v1.9. Thanks for the PR! ❤️

**Comment by kvart714** [comment]
yep, already downloaded and using! 😄
thx for the extension. changes are easy when the code is scalable 🔥
