### ISSUE TITLE
Extra character "-" in generated link to private repo makes URL 404

### ISSUE THREAD

**Issue by feegloo** [reduckted/GitWebLinks#15]
When I generate link to my private GitLab repo with "Copy Web Link to File", there is extra "-" character between repo name and "blob", which makes URL 404. Of course, I can manually delete "-".

Example:

`https://gitlab2.ams.creativecdn.net/ai-lab/incrementality-suite/-/blob/master/package.json`

should be:

`https://gitlab2.ams.creativecdn.net/ai-lab/incrementality-suite/blob/master/package.json`

--

I use below settings.json:

```
"gitweblinks.gitLabEnterprise": [
    {
        "baseUrl": "https://gitlab2.ams.creativecdn.net",
        "sshUrl": "git@gitlab2.ams.creativecdn.net"
    }
]
```

**Comment by reduckted** [comment]
Hi, thanks for the bug report. What edition and version of GitLab are you using? The community edition that I've set up for myself uses URLs with the "-". For example, http://localhost:8080/gitlab-instance-c7f59d2e/monitoring/-/blob/master/README.md

I'm not too familiar with GitLab, so perhaps there's a configuration option that I have set differently to your instance.

**Comment by feegloo** [comment]
GitLab Community Edition 11.7.0

Perhaps there is URL rewriting setup on server (in company I work in) or my GitLab version is not up-to-date (private server)
https://gitlab.com/gitlab-org/quality/performance/-/issues/216 <= maybe its this

Any additional setting to fix this problem would be great.

**Comment by feegloo** [comment]
Seems to work fine in GitLab Community Edition 13.7.4
