### ISSUE TITLE
Quick link opening

### ISSUE THREAD

**Issue by kvart714** [reduckted/GitWebLinks#19]
I use the extension every day. But almost always, when I copy a link, I want to open my browser and paste this to open it.
I added 'Open in Web' button when copying

[Pull request](https://github.com/reduckted/vscode-gitweblinks/pull/18)

maybe add an 'open/copy' option to the settings?

**Comment by reduckted** [comment]
This is now available in v2.2.0 which has just been published to the marketplace.

I've also implemented your idea of adding a setting for copying vs opening. There are two new settings that control whether the existing "Copy Link" menu item is shown (on by default) and whether a new "Open Link" menu item is shown (off by default). More details are in [the readme](https://github.com/reduckted/vscode-gitweblinks/blob/18140e6e64770c7e8e40e0f269b9fc28788b7522/README.md#open-in-browser).

Thanks again for the contribution. 🎉

**Comment by kvart714** [comment]
I have a couple more ideas, I'll check them as soon as the time appears 😊
