### ISSUE TITLE
Broken extension: Missing link in right-click menu; Cmd+Shift+P produces workspace error.

### ISSUE THREAD

**Issue by rubengmurray** [reduckted/GitWebLinks#20]
`Copy Web Link To File` has completely disappeared from my right-click menu in VS Code (first noticed 2/3 weeks ago).

Reading through https://marketplace.visualstudio.com/items?itemName=reduckted.vscode-gitweblinks I noticed you can also use the extension via the Command Palette, but when I try and execute any of the commands listed I get a workspace error

`The workspace at 'file:///Users/my_user/dev/ruben' is not tracked by Git.`

I might use workspaces in a different way to others, but I usually have a big folder open as the root of the workspace (e.g. `work`) which contains a lot of individual repos (e.g. `work/user-microservice`, `work/some-other-microservice` ). 

This seemed to pose no issues up until a few weeks ago. 

The error reads as if the extension is no longer looking through the directories to find the `.git` folder closest to the file I'm trying to create a link for, instead it just looks into the root of the workspace folder and errors. I'm presuming this is the same reason the option has disappeared from the menu.

Git Web Links For VS Code: 
`2.0.0 (2020-12-30)`
_(looks like a version was released that co-incided with my issue, time-wise)_

VS Code:
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

**Comment by rubengmurray** [comment]
It looks like there were a bunch of changes around Workspace / Repository management in this diff. 

https://github.com/reduckted/vscode-gitweblinks/compare/v1.9.0...v2.0.0

**Comment by rubengmurray** [comment]
OK very strange. I've tried installing `1.9.0` & `1.8.1` to see if the link re-appears and it doesn't. Same errors occur. Could be a conflict with another extension maybe? 

FYI, I'm using `Git Blame`, which seems to be working absolutely fine.

**Comment by reduckted** [comment]
Thanks for the bug report!

> I might use workspaces in a different way to others, but I usually have a big folder open as the root of the workspace (e.g. `work`) which contains a lot of individual repos (e.g. `work/user-microservice`, `work/some-other-microservice`).

Ah, I hadn't considered using VS Code that way, but I can definitely see why that would be useful.

> The error reads as if the extension is no longer looking through the directories to find the .git folder closest to the file I'm trying to create a link for, instead it just looks into the root of the workspace folder and errors. I'm presuming this is the same reason the option has disappeared from the menu.

Yeah, that's right, although previous versions also looked up from the root of the workspace (i.e. the `work` folder), so it's odd that it used to work for you. 😕 

I can make the commands look up from the file you're creating the link for, which will make the commands work when you run them from the command palette. I'll see if I can work out a performance-friendly way to detect that there's a Git repository somewhere in the workspace as well, so that the menu item can appear in the context menu.

As a workaround for now, you can try using a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) where each repository is added as a workspace.

**Comment by rubengmurray** [comment]
Yeah it did used to work, but I can't say that I was using the extension with VS Code for too long with it working, it was probably only a month maximum.

That would be great if you could find a way to at least get it working from the command palette, I really miss it now it's not available.

As a real world example I have 72 repositories inside my `work` folder, and I may be in `work/microservice/src/dir/file.ts` & want to link to something in there.

Thanks for the suggestion of multi-root workspaces - I'll have a read. I'm always a bit reticent to make changes to things like that when it adjusts a nice familiar (and easy!) pattern locally. I guess I should read about workspaces more generally to find out if I'm missing out on any other benefits from using VS Code in the way I do.

Nice one for the quick response and thanks for maintaining this extension.

**Comment by reduckted** [comment]
I've just published v2.1.0 to the marketplace which should fix this problem. 🎉 

 The commands should now work from the command palette _and_ the context menu item should be visible if there's a repository within the workspace.

**Comment by rubengmurray** [comment]
Hi @reduckted, 

I just updated to 2.1 and I do see the option appearing in the menu now, but I am receiving this error:

`The file 'file:///Users/user/dev/dir/project/src/file.ts' is not tracked by Git.`

&

`Unable to find the repository for the workspace.`

Two separate popups.... 

The file is definitely tracked by git. I've tested out a couple of project directories in different workspaces.

Same with attempting from the command palette

**Comment by assafmo** [comment]
> Hi @reduckted,
> 
> I just updated to 2.1 and I do see the option appearing in the menu now, but I am receiving this error:
> 
> `The file 'file:///Users/user/dev/dir/project/src/file.ts' is not tracked by Git.`
> 
> &
> 
> `Unable to find the repository for the workspace.`
> 
> Two separate popups....
> 
> The file is definitely tracked by git. I've tested out a couple of project directories in different workspaces.
> 
> Same with attempting from the command palette

This happens to me as well!

**Comment by reduckted** [comment]
@rubengmurray @assafmo That problem should be fixed in v2.1.1 which is now on the marketplace.

There was different behavior in Node.js between Windows and Linux that meant this bug slipped through. 😳

**Comment by assafmo** [comment]
@reduckted Thank you! Yeah I'm on Linux, I'll check it out and report back.

And also thank you for this awesome extension! ❤️

**Comment by rubengmurray** [comment]
Fantastic work @reduckted. Works like a charm.

**Comment by assafmo** [comment]
Yup, works for me too!
