### ISSUE TITLE
Doesn't work with Git worktrees

### ISSUE THREAD

**Issue by ecraig12345** [reduckted/GitWebLinks#21]
If I open the root folder of a [Git worktree](https://git-scm.com/docs/git-worktree) in VS Code, open a file, and try to use any of the commands to copy a link, I get an error `The workspace at 'file:///Users/me/git/my-repo-worktree' is not tracked by Git.` The commands work fine in the main local copy of the same repo.

Worktrees are implemented with a `.git` *file* which points to the the actual directory:
```
/my-repo-worktree
  .git            file with contents: 
                  gitdir: /(actual path here)/my-repo/.git/worktrees/my-repo-worktree

/my-repo
  .git/
    worktrees/
      my-repo-worktree/
        (normal .git folder stuff)
```

So this line ought to allow `.git` to be *either* a file or directory. 
https://github.com/reduckted/vscode-gitweblinks/blob/d7bc2db7102f07032f5af2262bfd83942fdb86c4/src/repository-finder.ts#L64

Then if all you're doing is running git commands, that can be done from the root of the worktree. (Only need to bother with looking in `my-repo/.git/worktrees/my-repo-worktree/` if you need to dig into the .git folder contents, which I'd guess isn't needed?)

**Comment by reduckted** [comment]
This is now available in v2.1.0 which has just been published to the marketplace.

Thanks again for the contribution, @ecraig12345! 😁
