### ISSUE TITLE
Incorrect link format for remote URLs containing username

### ISSUE THREAD

**Issue by skonotopovMarketer** [reduckted/GitWebLinks#229]
First of all, thank you very much for creating this super-useful extension!

I think the situations are not uncommon when a person can have more than one GitHub account - there can be several accounts for work and at least one personal.

To allow SSH find the right key for the account used for the repo, the remote URL must contain the username. In other words, in the local git config the URL is written like so:
```
[remote "origin"]
  url = git@github.com-username:account_name/repo.git
```

But when Git Web Links creates a link, I believe it mistakenly includes the username:
```
https://github.com/-username:account_name/repo/blob/123abc/path/to/file.rb#L123
```

A correct link will not contain the username:
```
https://github.com/account_name/repo/blob/123abc/path/to/file.rb#L123
```

Do you think it's possible to fix this?

**Comment by reduckted** [comment]
Interesting. I can't find any documentation about that particular format. Is that specific to GitHub, or is that just the way you've configured your SSH hosts?

**Comment by skonotopovMarketer** [comment]
Thank you very much for replying.

I went digging too and found out that what I was using to solve the problem of using different GitHub accounts for different repos was actually a hack 🤦

It was done by adding custom hosts to `~/.ssh/config`:
```
Host github.com-username
  Hostname github.com
  User git
  IdentityFile ~/.ssh/github-username.id_rsa
```

GitHub actually has documentation about managing multiple accounts [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/managing-multiple-accounts), I'm going to use that.

Sorry for the trouble!

**Comment by skonotopovMarketer** [comment]
UPD: In case someone has this problem, here is a solution.

Add to your local `project/.git/config`:
```
[core]
  sshCommand = ssh -i ~/.ssh/your_github_account_public_key -o IdentitiesOnly=yes
```
