### ISSUE TITLE
Not tracked files in v2.1.0.

### ISSUE THREAD

**Issue by merkuriy** [reduckted/GitWebLinks#23]
After last update to v2.1.0.

Message for all files: The file 'file:///home/…file.json' is not tracked by Git. Everything worked well before.

URL settings have been updated from baseUrl/sshUrl to http/ssh:
```json
"gitweblinks.gitLabEnterprise": [
  {
    "http": "https://git.example.ru/reps/rep1",
    "ssh": "git@git.example.reps/rep1.git"
  }
],
```

**Comment by reduckted** [comment]
Sorry about that. This is fixed in v2.1.1 that has just been published to the marketplace. 

There was different behavior in Node.js between Windows and Linux that meant this bug slipped through.
