### ISSUE TITLE
Support for gitea server or custom links?

### ISSUE THREAD

**Issue by martinhoess** [reduckted/GitWebLinks#269]
I am currently looking for a solution for links to files/commits in [gitea](https://about.gitea.com/) repos.

Would it be possible to extend this extension for this? ([Example repos](https://try.gitea.io/))
or generally to custom links where you can build your own link with placeholders?

**Comment by reduckted** [comment]
> Would it be possible to extend this extension for this?

Absolutely! Looks like the link format is simple enough, so shouldn't be too difficult.

**Comment by reduckted** [comment]
This is now available in v2.11.0.

You will need to specify your Gitea server in the settings. See the [Visual Studio](https://github.com/reduckted/GitWebLinks/blob/master/visual-studio/README.md#on-premise-servers) or [VS Code](https://github.com/reduckted/GitWebLinks/blob/master/vscode/README.md#gitea) readme for more info.

**Comment by martinhoess** [comment]
Tried it out, works wonderfully.

Thank you!
