### ISSUE TITLE
Links to multi-line selections on GitHub include an extra line

### ISSUE THREAD

**Issue by dhimmel** [reduckted/GitWebLinks#32]
If I select two lines in VSCode (say 462 and 463) and "Copy Link to Selection", I end up with the following anchor in the GitHub URL `#L462-L464`. Instead, this should be `#L462-L463`

**Comment by reduckted** [comment]
Thanks for the bug report! Fixed in v2.5.1.

**Comment by dhimmel** [comment]
Thanks. Linking to the relevant commit https://github.com/reduckted/vscode-gitweblinks/commit/ffe86744992b6bdeddf8319b878a728f9eb2ce4c.
