### ISSUE TITLE
Link to rendered GitHub files should include `?plain=1`

### ISSUE THREAD

**Issue by dhimmel** [reduckted/GitWebLinks#33]
From [Parameter to disable markdown rendering](https://github.blog/changelog/2021-06-30-parameter-to-disable-markdown-rendering/), GitHub introduced a new URL parameter on June 30, 2021:

> Appending `?plain=1` to the url for any Markdown file will now display the file without rendering. As with other code files, it will also show line numbers, and can be used to link other users to a specific line or lines. For example, appending `?plain=1#L52` will highlight line 52 of a plain text Markdown file.

It would be great if links to selection in markdown files could use `plain=1`, since otherwise they will have no effect.

**Comment by reduckted** [comment]
Thanks for the info. I've added this v2.5.1 which is available in the marketplace now.

**Comment by dhimmel** [comment]
Thanks! Noting https://github.com/reduckted/vscode-gitweblinks/commit/f1ec8829ffec204d13ca44c4cedd50db480675d2 as the relevant commit.

**Comment by dhimmel** [comment]
It looks like https://github.com/reduckted/vscode-gitweblinks/commit/f1ec8829ffec204d13ca44c4cedd50db480675d2 adds `?plain=1` to every GitHub URL, even those that default to plain rendering.

The downside is that it looks like `?plain=1` suppresses [embedded code snippets](https://github.blog/2017-08-15-introducing-embedded-code-snippets/) in GitHub comments. See the following URLs and how they render:


`https://github.com/reduckted/vscode-gitweblinks/blob/1384c1e5ee29d3b57ae3fbb31fd9140f3e7fadcc/shared/handlers/bitbucket-server.json#L6-L7`

https://github.com/reduckted/vscode-gitweblinks/blob/1384c1e5ee29d3b57ae3fbb31fd9140f3e7fadcc/shared/handlers/bitbucket-server.json#L6-L7

`https://github.com/reduckted/vscode-gitweblinks/blob/1384c1e5ee29d3b57ae3fbb31fd9140f3e7fadcc/shared/handlers/bitbucket-server.json?plain=1#L6-L7`

https://github.com/reduckted/vscode-gitweblinks/blob/1384c1e5ee29d3b57ae3fbb31fd9140f3e7fadcc/shared/handlers/bitbucket-server.json?plain=1#L6-L7

`https://github.com/reduckted/vscode-gitweblinks/blob/1384c1e5ee29d3b57ae3fbb31fd9140f3e7fadcc/README.md?plain=1#L14-L16`

https://github.com/reduckted/vscode-gitweblinks/blob/1384c1e5ee29d3b57ae3fbb31fd9140f3e7fadcc/README.md?plain=1#L14-L16

IMO this is a GitHub bug. `?plain=1` should not suppress embedded code snippets (I emailed support). But since it does, I wonder if `?plain=1` should only be added to files ending with `.md` or `.markdown`?

**Comment by lalten** [comment]
@reduckted the plain is a pain because I need to manually remove it to get the previews as @dhimmel shows. Any chance this could be made configurable, or @dhimmel's suggestion implemented?

**Comment by reduckted** [comment]
I've improved this in 4b1b35e033c6848af946569e3196ca913673e565. The `?plain=1` is only added to markdown files (`.md` or `.markdown`).

Version 2.5.3 should be available on the marketplace shortly.
