### ISSUE TITLE
Special characters in file name should be encoded

### ISSUE THREAD

**Issue by pddg** [reduckted/GitWebLinks#34]
## Environment

- macOS 11.4
- VSCode 1.58.0
- Git Web Links for VSCode 2.5.1

## Expected behavior

There is a file with a name like the `sample.json#etc`.
The generated url for the file should be `https://github.com/user/repo/blob/commit/sample.json%23etc`. 
This `#` is part of the filename, not a URL fragment, so it should be encoded.

## Actual behavior

The generated url for the file is `https://github.com/user/repo/blob/commit/sample.json#etc`.
Therefore, it will not work as a correct link.

## Note

Other characters that can be used in file names and are special in URLs (such as `?` etc.) are not encoded as well.

**Comment by reduckted** [comment]
I've almost fixed this, but ran into a problem with opening the URL from within VS Code. Looks like it's related to these issues:
* https://github.com/microsoft/vscode/issues/112577
* https://github.com/microsoft/vscode/issues/85930

I'll investigate what workarounds I can put in place and hopefully get a fix out soon.

**Comment by reduckted** [comment]
Should now be fixed in v2.5.2.
