### ISSUE TITLE
Feature request: Short SHA Links

### ISSUE THREAD

**Issue by lalten** [reduckted/GitWebLinks#38]
It would be awesome to (optionally?) shorten the links pointing at specific commits by using the `--short` option on git rev-parse.
See https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortlength

Here's a link with a full SHA as currently generated:
https://github.com/reduckted/GitWebLinks/blob/3cb46cb99f2657d1e8e70c32de571df7a29e656b/vscode/src/link-handler.ts#L273

The same link again but with a short SHA:
https://github.com/reduckted/GitWebLinks/blob/3cb46c/vscode/src/link-handler.ts#L273

So It looks like GH's preview feature only works with full SHAs, but it's still nice to have the short one to send to humans or to link in code.

**Comment by reduckted** [comment]
Sounds like a good idea. I'll take a look into it.

**Comment by reduckted** [comment]
I've just published v2.7.0 which has this feature in it. Look for a new setting called "Use short SHA hashes".

Commit cb71b8c0060b6ac2ff762435359ceb80569e8663
