### ISSUE TITLE
Change default remote

### ISSUE THREAD

**Issue by klkl0808** [reduckted/GitWebLinks#39]
I downloaded the plugin yesterday and I'm excited about it, because I like to send code links. This simplifies my process a lot. Thanks for developing!

I see that `origin` is picked as the default remote [1]. And this seems like a good decision given how git is typically used. But in repositories with more than one remote, it would be nice to have a way of picking a repository.

A minimal (but maybe not very) way of supporting this would be to pick with the highest priority a remote name like `GitWebLinks`. Then, the user can just add that additional remote to the repository and decide for every repository which remote should be used by default. Of course, other more configurable options would be nice. But maybe this suggestion is suited best for a quick upgrade.

[1] https://github.com/reduckted/GitWebLinks/blob/b200985aedfa612c4948d8fd776db993044eb69e/vscode/src/repository-finder.ts#L244

**Comment by reduckted** [comment]
Great idea!

**Comment by reduckted** [comment]
I've just published v2.7.0 which contains this feature. Look for a setting called "preferredRemoteName".

Commit 117b91af5760d2899e4841dcc6d720f9be450806

**Comment by klkl0808** [comment]
Works perfectly. Thanks for the amazing turn-around time!!!
