### ISSUE TITLE
request supports for workspace settings

### ISSUE THREAD

**Issue by tellok** [reduckted/GitWebLinks#41]
is is possible to add supporting for vscode workspace setting support, by this feature, we are able to sync repository config between team members, to avoid telling everyone how to config the plugin.

**Comment by tellok** [comment]
[√] it is ok, when we open project folders directly
[x] it is not ok, when we open project as a workspace

![image](https://user-images.githubusercontent.com/5621862/174992631-88bd789c-a0cb-444f-8e31-920c6b1f96cf.png)

**Comment by reduckted** [comment]
If you're using a workspace file (a `.code-workspace` file), then that workspace file has its own settings. Take a look here: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings
