### ISSUE TITLE
[Feature Suggestion] - Keyboard Shortcut for `Copy Link to Selection`

### ISSUE THREAD

**Issue by rubengmurray** [reduckted/GitWebLinks#44]
It would be useful if there was a keyboard short for the `Copy Link to Selection` menu item. Is there a way to bundle one into the extension? 

I've added one manually on my own machine via `keybindings.json` mapped to `cmd+g cmd+l`. 

<img width="283" alt="Screenshot 2022-08-20 at 23 56 02" src="https://user-images.githubusercontent.com/31162373/185768827-b01be581-f40d-43b7-b247-722c4c3b2d2b.png">

**Comment by reduckted** [comment]
Released in v2.8.0.
