### ISSUE TITLE
Regression: broken "find next" command in MacOS because of keyboard shortcut hijacking (CMD + G)

### ISSUE THREAD

**Issue by danielweck** [reduckted/GitWebLinks#47]
Culprit commit:
https://github.com/reduckted/GitWebLinks/commit/e42e29a431f2398845440b7147710233672441f9

I discovered this bug by opening "Toggle Keyboard Shortcuts Troubleshooting" in Visual Studio Code's command palette (SHIFT + CMD + P).

My workaround is to disable your extension (unfortunately), so I can continue to use my essential "find next" keyboard shortcut.

**Comment by reduckted** [comment]
You can remove a key binding by editing `keybindings.json`. Take a look at the docs here: https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

**Comment by danielweck** [comment]
Ah, I found a workaround :)

Launch "Open Keyboard Shortcuts (JSON)" from Visual Studio's command palette (SHIFT + CMD + P), then add this object in the JSON array:
```json
{ "key": "cmd+g",                 "command": "editor.action.nextMatchFindAction"},
```

(this will override / take precedence over default keyboard shortcuts, including those set by installed extensions)

**Comment by danielweck** [comment]
> You can remove a key binding by editing keybindings.json. Take a look at the docs here: https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

Thanks for the tip! I am now using the "minus" notation to disable your extension's keyboard shortcut :)

**Comment by reduckted** [comment]
I will look at changing that default keybinding though, since "find next" is a pretty important command. 😄

**Comment by reduckted** [comment]
Because of the conflict with the default <kbd>Ctrl</kbd>+<kbd>G</kbd> keybinding, I'm going to change the keybinding to:
* Windows: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>L</kbd>
* Mac: <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>L</kbd> 

That doesn't conflict with anything on Windows or Linux. I don't have a Mac, but based on the [default keybindings for macOS](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf), I believe it also doesn't conflict with any of the default bindings for macOS. Am I correct in that assumption?

/cc @rubengmurray

**Comment by rubengmurray** [comment]
Ah, oops. Sorry about that (esp. to OP).

Mac: `Cmd`+`Alt` (`Option`) +`L`: this seems to highlight a row when the finder is open (after `Cmd` + `F`) when a file is open.

On Mac: `Cmd` + `Control` + `L` seems to be spare on Mac.

**Comment by reduckted** [comment]
@rubengmurray Not a problem. 😄 

Thanks for confirming. I'll change it to <kbd>Cmd</kbd>+<kbd>Ctrl</kbd>+<kbd>L</kbd> on macOS.

Of course, that's just the default keybinding. You can always change it back to the original <kbd>Ctrl</kbd>+<kbd>G</kbd>,<kbd>Ctrl</kbd>+<kbd>L</kbd> (or anything else) if that's what you prefer.
