### ISSUE TITLE
Server URI is not a valid URI

### ISSUE THREAD

**Issue by FernandoMiguel** [reduckted/GitWebLinks#48]
```log
GitHub Enterprise Server URI is not a valid URI: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "git.drillinginfo.com", query: "", fragment: ""}
```

```yaml
  "gitweblinks.gitHubEnterprise": [
    {
      "http": "https://git.drillinginfo.com",
    }
  ],
```

**Comment by reduckted** [comment]
Hi @FernandoMiguel, are you able to post the output of the GitWebLinks window (you can obfuscate any file paths if you want to).

**Comment by FernandoMiguel** [comment]
@reduckted i am not sure what you mean or call "GitWebLinks window"

**Comment by reduckted** [comment]
Sorry, I left a word out. I meant the GitWebLinks _output_ window. 
![image](https://user-images.githubusercontent.com/10321525/202170585-c91229c9-694e-42d0-b9ac-f43b59d97303.png)

**Comment by FernandoMiguel** [comment]
![image](https://user-images.githubusercontent.com/168366/202171697-ca0d684b-8928-4ee6-8514-9a64b224c32d.png)

**Comment by FernandoMiguel** [comment]
I have several VS Code windows with different projects.
sometimes one works, but all others wont even show the option the right mouse menu.

**Comment by FernandoMiguel** [comment]
Version: 1.74.0-insider
Commit: edccbd1307ef8055f26778c5a86f9eef885bc6ff
Date: 2022-11-16T05:39:56.182Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**Comment by FernandoMiguel** [comment]
ofc now that i want debug logs, i can make it work everywhere..... just my luck... been failing for days and today cant reproduce.... _ffs_
