### ISSUE TITLE
GitLab and GitLab Enterprise

### ISSUE THREAD

**Issue by jonbrenner** [reduckted/GitWebLinks#5]
I forked and added a feature for adding GitLab and GLE. I can create a PR, but it would probably be just as easy for you to add. All that I did was copy the GitHubHandler and change the multiline selection code from #L1-L5 to #L1-5.

Let me know if you'd prefer that I submitted a PR.

**Comment by reduckted** [comment]
Fantastic, thanks for that! I've successfully got it working with https://gitlab.com repositories. I'll try to add support for on-premise GitLab servers soon, and then publish a new version.

**Comment by reduckted** [comment]
I've just published v1.7.0 to the marketplace which has support for both [gitlab.com](https://gitlab.com) and GitLab Enterprise Edition.

Let me know if you have any problems with it.
